"""Landing page style tokens."""

LANDING_COLORS = {
    "page_bg": "#FAFBFD",
    "header_bg": "white",
    "brand_primary": "#0B1A3A",
    "brand_secondary": "#666666",
    "text_primary": "#071B46",
    "text_secondary": "#4A4A4A",
    "button_primary_bg": "#E55A00",
    "button_primary_fg": "white",
    "button_secondary_bg": "white",
    "button_secondary_fg": "#1A1A1A",
    "badge_bg": "#FFEFD9",
    "badge_fg": "#A14E12",
    "card_bg": "white",
    "card_border": "#DDE3ED",
    "step_badge_bg": "#F05A00",
    "step_badge_fg": "white",
    "accent_panel_bg": "#D94B00",
    "accent_chip_bg": "#F27A3C",
    "accent_chip_fg": "white",
    "accent_text": "#FFF5F0",
    "highlight_bg": "#E9722F",
    "highlight_fg": "white",
    "panel_visual_bg": "#CF5A21",
    "panel_visual_fg": "#F6B08B",
    "muted_text": "#667085",
    "requirements_bg": "white",
    "requirements_border": "#DDE3ED",
    "timeline_line": "#D9E2F0",
    "timeline_dot_active": "#E55A00",
    "timeline_dot": "#F6A870",
}

LANDING_FONTS = {
    "brand_title": ("Segoe UI", 11, "bold"),
    "brand_subtitle": ("Segoe UI", 9),
    "nav_button": ("Segoe UI", 9),
    "nav_button_bold": ("Segoe UI", 9, "bold"),
    "hero_badge": ("Segoe UI", 11, "bold"),
    "hero_title": ("Segoe UI", 34, "bold"),
    "hero_body": ("Segoe UI", 13),
    "hero_button": ("Segoe UI", 12),
    "hero_button_bold": ("Segoe UI", 12, "bold"),
    "section_title": ("Segoe UI", 20, "bold"),
    "section_subtitle": ("Segoe UI", 10),
    "section_label": ("Segoe UI", 10, "bold"),
    "card_step": ("Segoe UI", 12, "bold"),
    "card_title": ("Segoe UI", 15, "bold"),
    "card_body": ("Segoe UI", 11),
    "panel_chip": ("Segoe UI", 10, "bold"),
    "panel_title": ("Segoe UI", 28, "bold"),
    "panel_body": ("Segoe UI", 11),
    "highlight_text": ("Segoe UI", 10, "bold"),
    "highlight_subtext": ("Segoe UI", 9),
    "panel_visual_icon": ("Segoe UI", 42, "bold"),
    "contact_title": ("Segoe UI", 12, "bold"),
    "contact_label": ("Segoe UI", 10, "bold"),
    "contact_value": ("Segoe UI", 10),
    "footer_note": ("Segoe UI", 9),
    "input_text": ("Segoe UI", 11),
}

LANDING_LAYOUT = {
    "header_pad_x": 32,
    "header_pad_y": 14,
    "hero_wrap": 920,
    "hero_min_height": 520,
    "hero_vertical_gap": 20,
    "hero_button_pad_x_primary": 30,
    "hero_button_pad_x_secondary": 28,
    "hero_button_pad_y": 11,
    "content_pad_x": 44,
    "card_wrap": 270,
    "card_min_height": 220,
    "card_pad_x": 18,
    "card_pad_y": 20,
    "cards_gap_x": 10,
    "cards_gap_y": 8,
    "section_gap_y": 24,
    "panel_text_wrap": 620,
    "panel_visual_size": 140,
    "contact_wrap": 220,
    "section_inner_pad_x": 36,
    "section_inner_pad_y": 20,
    "requirements_columns": 2,
    "timeline_steps": 4,
}

